customer/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Define more URL patterns as needed
]

dj_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),  
    path('', include('neograph.urls')),
]

neograph/urls.py
from django.urls import path
from neograph.views import SearchMitre
from neograph.viewsets import SearchByKeywords

app_name = 'neograph'

urlpatterns = [
    path(r'search_mitre/', SearchMitre.as_view(), name='search_mitre'),
    path(r'search/by_keywords/<str:keywords>/',SearchByKeywords.as_view(), name='search-by-keywords'), 

]

customer/models.py
from django.db import models

# Create your models here.

customer/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    title = 'Home'
    return render(request, 'customer/index.html',{'title': title})  # You can customize the template name and path
'''
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You have successfully logged in.')
            return redirect('customer:index')  # Redirect to the index page after successful login
        else:
            messages.error(request, 'Invalid username or password. Please try again.')
    return render(request, 'registration/login.html',{'title': 'Logins'})  # Replace 'registration/login.html' with your login template path
'''

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'You have successfully logged in.')
            return redirect('customer:index')  # Redirect to the index page after successful login
        else:
            messages.error(request, 'Invalid username or password. Please try again.')

    # Render the login page with error messages
    return render(request, 'registration/login.html', {'title': 'Logins'})

@login_required
def some_protected_view(request):
    return render(request, 'customer/protected.html')  # Example of a protected view accessible only to logged-in users

customer/templates/customer/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'customer/css/style.css' %}">
</head>

<body>
    <div >
        <a href="{% url 'customer:index' %}" class="btn btn-primary">Home</a>
        <a href="{% url 'neograph:search_mitre' %}" class="btn btn-primary">Search Mitre</a>
        <a href="{% url 'customer:logout' %}" class="btn btn-danger ">Logout</a> 
        {% if user.is_staff %}  
            <a href="{% url 'admin:index' %}" target="_blank" class="btn btn-secondary">Admin</a>
        {% endif %}
    </div>
    <div class="content">
        {% block content %}
        <!-- Content of child templates will appear here -->
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

customer/templates/customer/index.html
<!DOCTYPE html>
{% extends 'customer/base.html' %}
{% load static %}
{% block content %}
A simple app for MITRE search and visual presentation of TTPs.
{% endblock %}